# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(db_column='IdCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('direccion', models.TextField(blank=True, db_column='Direccion', null=True)),
                ('estado', models.CharField(max_length=2)),
                ('kg', models.IntegerField(blank=True, db_column='KG', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('iddetalle', models.AutoField(db_column='IdDetalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'detalleventa',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproductos', models.AutoField(db_column='IdProductos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('precio', models.DecimalField(blank=True, db_column='Precio', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventa', models.AutoField(db_column='IdVenta', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'managed': False,
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('favorite', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('idcliente', models.ForeignKey(db_column='IdCliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Clientes')),
            ],
        ),
    ]
