# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20170916_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='IdCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('direccion', models.TextField(blank=True, db_column='Direccion', null=True)),
                ('estado', models.CharField(max_length=2)),
                ('kg', models.IntegerField(blank=True, db_column='KG', null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproductos', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('precio', models.DecimalField(blank=True, db_column='Precio', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(db_column='IdVenta', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='idfoto',
            field=models.ForeignKey(db_column='IdCliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Cliente'),
        ),
    ]
